image: node:15.10.0-alpine3.12

stages:
  - build
  - deploy

build:
  stage: build
  only: 
    - sass
  tags:
    - production
  cache:
    key: ${CI_COMMIT_REF_SLUG}-npm
     paths:
      - node_modules/

  script:
    - npm install
    - npm run build

  artifacts:
    paths:
      - node_modules/
      - public/
    expire_in: 1 days
    when: always