image: tiangolo/docker-with-compose

services:
  - docker:dind

stages:
  - dev


dev:
  stage: dev
  only:
    - main
  tags:
    - dev
  script:
    - docker-compose build
    - docker-compose down
    - docker-compose up -d --force-recreate