stages:
  - build
  - deploy

build_dev:
  image: node:15.10.0-alpine3.12
  stage: build
  tags:
  - dev
  only:
  - main
  cache:
    key: ${CI_COMMIT_REF_SLUG}-npm
    paths:
      - node_modules/

  script:
      - npm install
      - npm run build


  artifacts:
    expire_in: 1 days
    paths:
      - node_modules/
      - public/

deploy_dev:
  stage: deploy
  tags:
    - dev
  only:
    - main
  image: tiangolo/docker-with-compose
  script:
    - docker-compose down
    - docker-compose up -d --force-recreate

########################################################

build_production:
  image: node:15.10.0-alpine3.12
  stage: build
  tags:
  - production
  only:
  - production
  cache:
    key: ${CI_COMMIT_REF_SLUG}-npm
    paths:
      - node_modules/

  script:
      - npm install
      - npm run build


  artifacts:
    expire_in: 1 hour
    paths:
      - node_modules/
      - public/

deploy_production:
  stage: deploy
  tags:
    - production
  only:
    - production
  image: tiangolo/docker-with-compose
  script:
    - docker-compose -f docker-compose.prod.yml down
    - docker-compose -f docker-compose.prod.yml up -d --force-recreate