image: tiangolo/docker-with-compose

services:
  - docker:dind

stages:
  - build
  - deploy

build:
  stage: build
  only: 
    - production
  tags:
    - production
  cache:
    key: ${CI_COMMIT_REF_SLUG}-npm
     paths:
      - node_modules/

  artifacts:
    paths:
      - node_modules/
    expire_in: 1 days
    when: always



deploy:
  stage: deploy
  only:
    - production
  tags:
    - production
  script:
    - docker-compose -f docker-compose.prod.yml build
    - docker-compose -f docker-compose.prod.yml down
    - docker-compose -f docker-compose.prod.yml up -d --force-recreate