stages:
  - build
  - deploy

build:
  image: node:15.10.0-alpine3.12
  stage: build
  tags:
  - dev
  only:
  - sass
  # Cache the `node_modules` folder
  # using the `npm` suffix on the key.
  cache:
    key: ${CI_COMMIT_REF_SLUG}-npm
    paths:
      - node_modules/

  # Install and compile.
  script:
      - npm install
      - npm run build

  # Provide the other jobs of the pipeline with
  # the node dependencies and the compiled assets.
  artifacts:
    expire_in: 1 month
    paths:
      - node_modules/
      - public/

deploy:
  stage: deploy
  only:
    - sass
  tags:
    - dev
  image: tiangolo/docker-with-compose
  script:
    - docker-compose down
    - docker-compose up -d --force-recreate