image: tiangolo/docker-with-compose

services:
  - docker:dind

stages:
  - test
  - deploy


step-uat:
  stage: test
  only:
    - uat
  tags:
    - uat
  script:
    - docker-compose up -d --build

step-deploy-staging:
  stage: deploy
  only:
    - staging
  tags:
    - staging
  script:
    - docker-compose -f docker-compose.staging.yml up -d --build

step-deploy-production:
  stage: deploy
  only:
    - production
  tags:
    - production
  script:
    - docker-compose -f docker-compose.prod.yml up -d --build
  when: manual
