stages:
  - build

docker-build:
  # Official docker image.
  image: tiangolo/docker-with-compose
  stage: build
  services:
    - docker:dind
  before_script:
    - docker info
  script:
    - docker-compose --version