image: tiangolo/docker-with-compose

services:
  - docker:dind

stages:
  - deploy



deploy:
  stage: deploy
  only:
    - production
  tags:
    - production
  script:
    - docker-compose -f docker-compose.prod.yml build
    - docker-compose -f docker-compose.prod.yml down
    - docker-compose -f docker-compose.prod.yml up -d --force-recreate