version: "3.8"

services: 

  node:
    build: 
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    labels:
            - "traefik.enable=true"
            - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
            - "traefik.http.routers.plebs.middlewares=redirect-to-https"
            - "traefik.http.routers.plebs.rule=Host(`node.freechampionrotations.com`)"
            - "traefik.http.routers.plebs.entrypoints=web"
            - "traefik.http.routers.plebs-secure.rule=Host(`node.freechampionrotations.com`)"
            - "traefik.http.routers.plebs-secure.tls=true"
            - "traefik.http.routers.plebs-secure.tls.certresolver=myresolver"
            - "traefik.docker.network=traefik-proxy"
    networks:
      - traefik-proxy

networks: 
  traefik-proxy:
    external: true