version: "3.8"

services: 

  node:
    build: 
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8000:8000
    networks:
      - traefik-proxy

networks: 
  traefik-proxy:
    external: true
