version: "3.8"

services: 

  node:
    build: 
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.lysmiljo.middlewares=redirect-to-https"
      - "traefik.http.routers.node.rule=Host(`node.freechampionrotations.com`)"
      - "traefik.http.routers.node.entrypoints=web"
      - "traefik.http.routers.node-secure.rule=Host(`node.freechampionrotations.com`)"
      - "traefik.http.routers.node-secure.tls=true"
      - "traefik.http.routers.node-secure.tls.certresolver=myresolver"
      - "traefik.docker.network=traefik-proxy"
    networks:
      - traefik-proxy

networks: 
  traefik-proxy:
    external: true
